🐛 Fix pitch computation
AlessioGr/NotQuests pull request #182
Opened 2023-01-23 18:56 UTC by BakaAless

Fix yaw.

2023-01-30 21:20 UTC, AlessioGr requested changes

2023-01-31 15:55 UTC, BakaAless commented on paper/src/main/java/rocks/gravili/notquests/paper/events/QuestEvents.java
> +        final ConversationPlayer currentOpenConversationPlayer = main.getConversationManager().getOpenConversation(player.getUniqueId());
> Also check if this potentially breaks any deliveritems objectives if, right before/after delivering the item, it opens a conversation

Deliver items task is checked before opening a conversation so, if the player is in a conversation, he already delivered item

2023-01-31 15:58 UTC, BakaAless commented on paper/src/main/java/rocks/gravili/notquests/paper/events/QuestEvents.java
> +        final ConversationPlayer currentOpenConversationPlayer = main.getConversationManager().getOpenConversation(e.getPlayer().getUniqueId());
Resolved in the new commit

2023-01-31 15:58 UTC, BakaAless commented on paper/src/main/java/rocks/gravili/notquests/paper/events/QuestEvents.java
> +        final ConversationPlayer currentOpenConversationPlayer = main.getConversationManager().getOpenConversation(player.getUniqueId());
Resolved in the new commit

2023-01-31 20:06 UTC, merged